- http://www.apodiscounter.de/partnerprogramme/krn.csv:
   shopname: apodiscounter
   delimetr: ;
   product_id_column: 0
   price_column: 1
- http://preisexporte.apobyte.de/www.eurapon.de/preissuchmaschine/preissuchmaschine.csv:
   shopname: eurapon
   delimetr: "\t"
   product_id_column: 0
   price_column: 3
